apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "research.fullname" . }}
  labels:
    {{- include "research.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.env }}
  {{ $name }}: {{ if kindIs "map" $value }}{{ $value | toJson | quote }}{{ else }}{{ $value | toString | quote }}{{ end }}
  {{- end }}
