{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "research.fullname" . }}
  labels:
    {{- include "research.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    {{- include "research.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
{{- end }}
