{{- if and .Values.api.enabled .Values.api.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "research.fullname" . }}
  labels:
    {{- include "research.labels" . | nindent 4 }}
    {{- with .Values.api.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "research.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.api.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.api.serviceMonitor.scrapeTimeout }}
{{- end }}
